### ISSUE TITLE
Lists and codeblocks in notes not working correctly

### ISSUE THREAD

**Issue by ru-fu** [canonical/discourse-markdown-note#16]
When adding a list inside a note in Discourse, the list isn't rendered correctly. It looks acceptable as long as the opening and closing tags are on separate lines, but the list isn't rendered as actual list but just as lines.

Test here: https://discourse.ubuntu.com/t/navigation-update/24341

Input:
![image](https://user-images.githubusercontent.com/11227796/172810511-e0aa5a82-9959-4e6b-9d21-3bc8a1ed0779.png)

Output (Discourse):
![image](https://user-images.githubusercontent.com/11227796/172810348-312282ea-4c51-4cc9-b0cf-484eee4d8233.png)

**Comment by ru-fu** [comment]
When adding a codeblock inside a note, it loses all spaces.
See here for an example: https://discourse.ubuntu.com/t/how-to-implement-a-web-based-streaming-client/21835

**Comment by ru-fu** [comment]
Thanks @carkod !
Now, how can this be activated for the Anbox Cloud docs?

An example is here: https://anbox-cloud.io/docs/tut/getting-started-dashboard

**Comment by nottrobin** [comment]
@ru-fu [This is the RT](https://portal.admin.canonical.com/C155140) asking for it to be rolled out. We've asked for it to be done on January 5th, so we don't experience unexpected issues over the holiday season, when support would be difficult.

**Comment by ru-fu** [comment]
Great - thanks @nottrobin !
